name: RAG Evaluation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
          WEAVIATE_URL: ${{ secrets.WEAVIATE_URL }}
          WEAVIATE_API_KEY: ${{ secrets.WEAVIATE_API_KEY }}
jobs:
  rag-eval:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install uv
          uv sync

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh

      - name: Start Ollama
        run: |
          ollama serve > ollama.log 2>&1 &
          sleep 5

      - name: Pull models
        run: |
          ollama pull phi3:mini
          ollama pull llama3.2

      - name: Debug Python environment
        run: |
          which python
          python --version
          pip --version
          pip list

      - name: Run evaluation
        run: |
          uv run python evaluation/evaluate_rag.py